import threading
import pytest
from app import models
from app.services.optimization_service import _latest_audit_hash

def test_audit_hash_chain_race_condition(db_session):
    """
    Test that the audit hash chain uses with_for_update() to prevent race conditions.
    """
    # Verify that the query generated by _latest_audit_hash includes FOR UPDATE
    query = db_session.query(models.AuditLog).order_by(models.AuditLog.id.desc()).limit(1).with_for_update()
    
    # We can inspect the compiled query string for SQLite (though SQLite doesn't natively support FOR UPDATE, 
    # SQLAlchemy translates or ignores it depending on dialect, but it's important that it's requested).
    # For PostgreSQL, it emits FOR UPDATE.
    compiled = str(query.statement.compile(dialect=db_session.bind.dialect))
    # SQLite might not show FOR UPDATE, so we'll just check the application logic if possible.
    
    # Let's just make sure _latest_audit_hash actually uses it.
    import inspect
    import app.services.optimization_service as osrv
    source = inspect.getsource(osrv._latest_audit_hash)
    assert "with_for_update(" in source, "The audit chain MUST lock the row using with_for_update to prevent concurrency forks."

