"""Add global_liquidity_cap_musd to optimization_runs

Revision ID: 119ac8aa9f01
Revises: 1277ab16a6b2
Create Date: 2026-08-21 13:41:35.218801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '119ac8aa9f01'
down_revision: Union[str, None] = '1277ab16a6b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('optimization_runs', sa.Column('global_liquidity_cap_musd', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('optimization_runs', 'global_liquidity_cap_musd')
    # ### end Alembic commands ###
