"""initial schema

Revision ID: 1277ab16a6b2
Revises: 
Create Date: 2026-08-20 02:25:44.330092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1277ab16a6b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tools_used_json', sa.JSON(), nullable=True),
    sa.Column('sources_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_messages_session_id'), 'agent_messages', ['session_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('prev_hash', sa.String(), nullable=True),
    sa.Column('self_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currencies',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('optimization_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('run_type', sa.String(), nullable=True),
    sa.Column('solver', sa.String(), nullable=True),
    sa.Column('params_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_variables', sa.Integer(), nullable=True),
    sa.Column('total_terms', sa.Integer(), nullable=True),
    sa.Column('initial_energy', sa.Float(), nullable=True),
    sa.Column('final_energy', sa.Float(), nullable=True),
    sa.Column('runtime_ms', sa.Float(), nullable=True),
    sa.Column('random_seed', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('qubo_version', sa.String(), nullable=True),
    sa.Column('forecast_version', sa.String(), nullable=True),
    sa.Column('knowledge_version', sa.String(), nullable=True),
    sa.Column('convergence_json', sa.JSON(), nullable=True),
    sa.Column('constraint_violations_json', sa.JSON(), nullable=True),
    sa.Column('onehot_clean', sa.Boolean(), nullable=True),
    sa.Column('prev_hash', sa.String(), nullable=True),
    sa.Column('self_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corridors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_currency', sa.String(length=3), nullable=True),
    sa.Column('dest_currency', sa.String(length=3), nullable=True),
    sa.Column('settlement_window_start_hour_utc', sa.Integer(), nullable=True),
    sa.Column('settlement_window_end_hour_utc', sa.Integer(), nullable=True),
    sa.Column('cutoff_hour_utc', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dest_currency'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['source_currency'], ['currencies.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('overrides_json', sa.JSON(), nullable=True),
    sa.Column('result_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['result_run_id'], ['optimization_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stress_test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('scenario_name', sa.String(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('required_liquidity_musd', sa.Float(), nullable=True),
    sa.Column('recommended_liquidity_musd', sa.Float(), nullable=True),
    sa.Column('capital_released_musd', sa.Float(), nullable=True),
    sa.Column('capital_required_musd', sa.Float(), nullable=True),
    sa.Column('settlement_coverage', sa.Float(), nullable=True),
    sa.Column('shortfall_probability', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['optimization_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stress_test_results_batch_id'), 'stress_test_results', ['batch_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('is_demo_account', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('human_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['optimization_runs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('source_date', sa.String(), nullable=True),
    sa.Column('jurisdiction', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('citation', sa.String(), nullable=True),
    sa.Column('corridor_id', sa.Integer(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nostro_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corridor_id', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('institution_name', sa.String(), nullable=False),
    sa.Column('current_balance_musd', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], ),
    sa.ForeignKeyConstraint(['currency'], ['currencies.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('corridor_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('liquidity_musd', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['optimization_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_baselines_run_id'), 'optimization_baselines', ['run_id'], unique=False)
    op.create_table('optimization_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('corridor_id', sa.Integer(), nullable=True),
    sa.Column('current_liquidity_musd', sa.Float(), nullable=True),
    sa.Column('optimized_liquidity_musd', sa.Float(), nullable=True),
    sa.Column('capital_released_musd', sa.Float(), nullable=True),
    sa.Column('risk_before', sa.Float(), nullable=True),
    sa.Column('risk_after', sa.Float(), nullable=True),
    sa.Column('chosen_bucket_musd', sa.Float(), nullable=True),
    sa.Column('explanation_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['optimization_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_results_run_id'), 'optimization_results', ['run_id'], unique=False)
    op.create_table('payment_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corridor_id', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.Column('horizon_days', sa.Integer(), nullable=True),
    sa.Column('expected_demand_musd', sa.Float(), nullable=False),
    sa.Column('std_dev_musd', sa.Float(), nullable=False),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('ci_low_musd', sa.Float(), nullable=True),
    sa.Column('ci_high_musd', sa.Float(), nullable=True),
    sa.Column('forecast_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_forecasts_corridor_id'), 'payment_forecasts', ['corridor_id'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corridor_id', sa.Integer(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('amount_musd', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transactions_corridor_id'), 'payment_transactions', ['corridor_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_ts'), 'payment_transactions', ['ts'], unique=False)
    op.create_table('risk_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corridor_id', sa.Integer(), nullable=True),
    sa.Column('opportunity_cost_rate_annual', sa.Float(), nullable=True),
    sa.Column('loss_given_shortfall_musd', sa.Float(), nullable=True),
    sa.Column('fx_cost_bps', sa.Float(), nullable=True),
    sa.Column('operational_cost_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corridor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_parameters')
    op.drop_index(op.f('ix_payment_transactions_ts'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_corridor_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_payment_forecasts_corridor_id'), table_name='payment_forecasts')
    op.drop_table('payment_forecasts')
    op.drop_index(op.f('ix_optimization_results_run_id'), table_name='optimization_results')
    op.drop_table('optimization_results')
    op.drop_index(op.f('ix_optimization_baselines_run_id'), table_name='optimization_baselines')
    op.drop_table('optimization_baselines')
    op.drop_table('nostro_accounts')
    op.drop_table('knowledge_items')
    op.drop_table('human_approvals')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stress_test_results_batch_id'), table_name='stress_test_results')
    op.drop_table('stress_test_results')
    op.drop_table('scenarios')
    op.drop_table('corridors')
    op.drop_table('organizations')
    op.drop_table('optimization_runs')
    op.drop_table('currencies')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_agent_messages_session_id'), table_name='agent_messages')
    op.drop_table('agent_messages')
    # ### end Alembic commands ###
