"""Add composite index for payment transactions

Revision ID: 6ffa5cf51da7
Revises: c62cf3073dd0
Create Date: 2026-08-28 09:51:46.451896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '6ffa5cf51da7'
down_revision: Union[str, None] = 'c62cf3073dd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('optimization_constraints')
    op.drop_table('regulatory_rules')
    op.drop_table('optimization_variables')
    op.drop_table('qubo_models')
    op.drop_table('holidays')
    op.drop_table('recommendations')
    op.drop_table('model_versions')
    op.drop_table('convergence_history')
    op.drop_table('knowledge_chunks')
    op.drop_table('knowledge_sources')
    op.drop_table('liquidity_snapshots')
    op.drop_table('qubo_terms')
    op.drop_table('liquidity_requirements')
    op.drop_table('optimization_solutions')
    op.drop_table('roles')
    op.drop_table('stress_tests')
    op.drop_table('agent_sessions')
    op.drop_table('model_assumptions')
    op.drop_table('agent_tool_calls')
    op.drop_table('settlement_practices')
    op.drop_table('cutoff_times')
    op.drop_table('settlement_windows')
    op.drop_table('knowledge_documents')
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_knowledge_items_source_type'), 'knowledge_items', ['source_type'], unique=False)
    op.create_index(op.f('ix_optimization_runs_run_type'), 'optimization_runs', ['run_type'], unique=False)
    op.create_index('ix_payment_transactions_corridor_ts', 'payment_transactions', ['corridor_id', 'ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_transactions_corridor_ts', table_name='payment_transactions')
    op.drop_index(op.f('ix_optimization_runs_run_type'), table_name='optimization_runs')
    op.drop_index(op.f('ix_knowledge_items_source_type'), table_name='knowledge_items')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.create_table('knowledge_documents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('source_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settlement_windows',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('corridor_id', sa.INTEGER(), nullable=True),
    sa.Column('start_hour', sa.INTEGER(), nullable=True),
    sa.Column('end_hour', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cutoff_times',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('corridor_id', sa.INTEGER(), nullable=True),
    sa.Column('cutoff_hour', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settlement_practices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chunk_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_tool_calls',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message_id', sa.INTEGER(), nullable=True),
    sa.Column('tool_name', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['agent_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_assumptions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chunk_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('session_uuid', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stress_tests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('optimization_solutions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('run_id', sa.INTEGER(), nullable=True),
    sa.Column('solution_json', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['optimization_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liquidity_requirements',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('corridor_id', sa.INTEGER(), nullable=True),
    sa.Column('required_amount', sa.FLOAT(), nullable=True),
    sa.Column('computed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qubo_terms',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('model_id', sa.INTEGER(), nullable=True),
    sa.Column('i', sa.INTEGER(), nullable=True),
    sa.Column('j', sa.INTEGER(), nullable=True),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['qubo_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liquidity_snapshots',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('account_id', sa.INTEGER(), nullable=True),
    sa.Column('snapshot_time', sa.DATETIME(), nullable=True),
    sa.Column('balance', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['nostro_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_sources',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('document_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('convergence_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('run_id', sa.INTEGER(), nullable=True),
    sa.Column('iteration', sa.INTEGER(), nullable=True),
    sa.Column('energy', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['optimization_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('version_tag', sa.VARCHAR(), nullable=True),
    sa.Column('deployed_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('run_id', sa.INTEGER(), nullable=True),
    sa.Column('recommendation_text', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['optimization_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holidays',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('currency_code', sa.VARCHAR(length=3), nullable=True),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qubo_models',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('run_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['optimization_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_variables',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('run_id', sa.INTEGER(), nullable=True),
    sa.Column('variable_name', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['optimization_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regulatory_rules',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chunk_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_constraints',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('run_id', sa.INTEGER(), nullable=True),
    sa.Column('constraint_type', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['optimization_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
