"""Add decomposed loss parameters

Revision ID: aa5ae6e5f9dc
Revises: 119ac8aa9f01
Create Date: 2026-08-23 23:33:01.782755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa5ae6e5f9dc'
down_revision: Union[str, None] = '119ac8aa9f01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_tag', sa.String(), nullable=True),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stress_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_tool_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['agent_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('convergence_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('iteration', sa.Integer(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['optimization_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_constraints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('constraint_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['optimization_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_solutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('solution_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['optimization_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('variable_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['optimization_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qubo_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['optimization_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['optimization_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_uuid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cutoff_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corridor_id', sa.Integer(), nullable=True),
    sa.Column('cutoff_hour', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liquidity_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corridor_id', sa.Integer(), nullable=True),
    sa.Column('required_amount', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qubo_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('i', sa.Integer(), nullable=True),
    sa.Column('j', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['qubo_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settlement_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corridor_id', sa.Integer(), nullable=True),
    sa.Column('start_hour', sa.Integer(), nullable=True),
    sa.Column('end_hour', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liquidity_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_time', sa.DateTime(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['nostro_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_assumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regulatory_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settlement_practices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('risk_parameters', sa.Column('correspondent_penalty_fee', sa.Float(), nullable=True))
    op.add_column('risk_parameters', sa.Column('operational_remediation_cost', sa.Float(), nullable=True))
    op.add_column('risk_parameters', sa.Column('reputational_risk_proxy', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_parameters', 'reputational_risk_proxy')
    op.drop_column('risk_parameters', 'operational_remediation_cost')
    op.drop_column('risk_parameters', 'correspondent_penalty_fee')
    op.drop_table('settlement_practices')
    op.drop_table('regulatory_rules')
    op.drop_table('model_assumptions')
    op.drop_table('liquidity_snapshots')
    op.drop_table('settlement_windows')
    op.drop_table('qubo_terms')
    op.drop_table('liquidity_requirements')
    op.drop_table('knowledge_chunks')
    op.drop_table('cutoff_times')
    op.drop_table('agent_sessions')
    op.drop_table('recommendations')
    op.drop_table('qubo_models')
    op.drop_table('optimization_variables')
    op.drop_table('optimization_solutions')
    op.drop_table('optimization_constraints')
    op.drop_table('knowledge_documents')
    op.drop_table('holidays')
    op.drop_table('convergence_history')
    op.drop_table('agent_tool_calls')
    op.drop_table('stress_tests')
    op.drop_table('roles')
    op.drop_table('model_versions')
    op.drop_table('knowledge_sources')
    # ### end Alembic commands ###
