"""Add legal_reviewed column

Revision ID: c62cf3073dd0
Revises: aa5ae6e5f9dc
Create Date: 2026-08-24 11:56:28.810193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c62cf3073dd0'
down_revision: Union[str, None] = 'aa5ae6e5f9dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_items', sa.Column('legal_reviewed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_items', 'legal_reviewed')
    # ### end Alembic commands ###
