#!/usr/bin/env python3
# scripts/generate_synthetic_data.py
"""
NostroQ Synthetic Data Generator

Generates realistic synthetic data for demonstration:
- Corridor configurations
- Historical demand patterns
- FX rates
- Settlement windows
- Transaction records
- Bank configuration

DISCLOSURE: All data generated by this script is synthetic.
No real banking data is used or sourced.

Author: NostroQ Team
"""

import json
import random
import hashlib
import argparse
from datetime import datetime, timedelta
from pathlib import Path
from typing import List, Dict, Any, Optional, Tuple
from dataclasses import dataclass, asdict
import math

# Try to import optional dependencies
try:
    from faker import Faker
    FAKER_AVAILABLE = True
except ImportError:
    FAKER_AVAILABLE = False
    print("⚠ Faker not installed. Using basic random generation.")

try:
    import numpy as np
    NUMPY_AVAILABLE = True
except ImportError:
    NUMPY_AVAILABLE = False
    print("⚠ NumPy not installed. Using basic random generation.")

# =============================================================================
# CONFIGURATION
# =============================================================================

# Set seeds for reproducibility
RANDOM_SEED = 42
random.seed(RANDOM_SEED)
if NUMPY_AVAILABLE:
    np.random.seed(RANDOM_SEED)
if FAKER_AVAILABLE:
    Faker.seed(RANDOM_SEED)
    fake = Faker()

# Output directory
OUTPUT_DIR = Path("data")

# =============================================================================
# REALISTIC CONSTANTS
# =============================================================================

# Currency pairs commonly used in cross-border corridors
CORRIDOR_CONFIGS = [
    {
        "source": "USD", "dest": "INR",
        "avg_daily_volume": 45_000_000,
        "volatility": 0.15,
        "peak_multiplier": 2.5,
        "settlement_hours": (4, 14),  # UTC
        "cutoff_hour": 12
    },
    {
        "source": "EUR", "dest": "INR",
        "avg_daily_volume": 32_000_000,
        "volatility": 0.18,
        "peak_multiplier": 2.2,
        "settlement_hours": (5, 15),
        "cutoff_hour": 13
    },
    {
        "source": "GBP", "dest": "INR",
        "avg_daily_volume": 28_000_000,
        "volatility": 0.20,
        "peak_multiplier": 2.3,
        "settlement_hours": (5, 15),
        "cutoff_hour": 13
    },
    {
        "source": "AED", "dest": "INR",
        "avg_daily_volume": 22_000_000,
        "volatility": 0.08,
        "peak_multiplier": 1.8,
        "settlement_hours": (4, 12),
        "cutoff_hour": 10
    },
    {
        "source": "SGD", "dest": "INR",
        "avg_daily_volume": 18_000_000,
        "volatility": 0.12,
        "peak_multiplier": 2.0,
        "settlement_hours": (0, 10),
        "cutoff_hour": 8
    },
    {
        "source": "JPY", "dest": "INR",
        "avg_daily_volume": 15_000_000,
        "volatility": 0.22,
        "peak_multiplier": 2.4,
        "settlement_hours": (0, 8),
        "cutoff_hour": 6
    },
    {
        "source": "USD", "dest": "EUR",
        "avg_daily_volume": 52_000_000,
        "volatility": 0.10,
        "peak_multiplier": 2.0,
        "settlement_hours": (7, 17),
        "cutoff_hour": 15
    },
    {
        "source": "EUR", "dest": "USD",
        "avg_daily_volume": 48_000_000,
        "volatility": 0.10,
        "peak_multiplier": 2.0,
        "settlement_hours": (13, 21),
        "cutoff_hour": 19
    },
    {
        "source": "USD", "dest": "GBP",
        "avg_daily_volume": 38_000_000,
        "volatility": 0.14,
        "peak_multiplier": 2.1,
        "settlement_hours": (7, 17),
        "cutoff_hour": 15
    },
    {
        "source": "GBP", "dest": "EUR",
        "avg_daily_volume": 15_000_000,
        "volatility": 0.16,
        "peak_multiplier": 1.9,
        "settlement_hours": (7, 16),
        "cutoff_hour": 14
    },
    {
        "source": "USD", "dest": "CHF",
        "avg_daily_volume": 8_000_000,
        "volatility": 0.10,
        "peak_multiplier": 1.7,
        "settlement_hours": (7, 16),
        "cutoff_hour": 14
    },
]

# Correspondent banks by currency (realistic names, synthetic details)
CORRESPONDENT_BANKS = {
    "INR": [
        {"name": "HDFC Bank", "swift": "HDFCINBB", "city": "Mumbai", "rating": "A"},
        {"name": "ICICI Bank", "swift": "ABORINBB", "city": "Mumbai", "rating": "A"},
        {"name": "State Bank of India", "swift": "SBININBB", "city": "Mumbai", "rating": "A"},
        {"name": "Axis Bank", "swift": "AXISINBB", "city": "Mumbai", "rating": "A-"},
    ],
    "USD": [
        {"name": "JPMorgan Chase", "swift": "CHASUS33", "city": "New York", "rating": "A+"},
        {"name": "Citibank", "swift": "CITIUS33", "city": "New York", "rating": "A"},
        {"name": "Bank of America", "swift": "BOFAUS3N", "city": "New York", "rating": "A"},
    ],
    "EUR": [
        {"name": "Deutsche Bank", "swift": "DEUTDEFF", "city": "Frankfurt", "rating": "A-"},
        {"name": "BNP Paribas", "swift": "BNPAFRPP", "city": "Paris", "rating": "A"},
        {"name": "ING Bank", "swift": "INGBNL2A", "city": "Amsterdam", "rating": "A"},
    ],
    "GBP": [
        {"name": "Barclays", "swift": "BARCGB22", "city": "London", "rating": "A"},
        {"name": "HSBC", "swift": "MIDLGB22", "city": "London", "rating": "A+"},
        {"name": "Lloyds Bank", "swift": "LOYDGB2L", "city": "London", "rating": "A"},
    ],
    "AED": [
        {"name": "Emirates NBD", "swift": "ABORAEAA", "city": "Dubai", "rating": "A-"},
        {"name": "First Abu Dhabi Bank", "swift": "NBADAEAA", "city": "Abu Dhabi", "rating": "A"},
    ],
    "SGD": [
        {"name": "DBS Bank", "swift": "DBSSSGSG", "city": "Singapore", "rating": "A+"},
        {"name": "OCBC Bank", "swift": "OCBCSGSG", "city": "Singapore", "rating": "A+"},
    ],
    "JPY": [
        {"name": "MUFG Bank", "swift": "BOABORJ", "city": "Tokyo", "rating": "A"},
        {"name": "Sumitomo Mitsui", "swift": "SMBCJPJT", "city": "Tokyo", "rating": "A"},
    ],
    "CHF": [
        {"name": "UBS", "swift": "UBSWCHZH", "city": "Zurich", "rating": "A+"},
        {"name": "Credit Suisse", "swift": "CRESCHZZ", "city": "Zurich", "rating": "A-"},
    ],
}

# Base FX rates (approximate mid-market rates)
BASE_FX_RATES = {
    "USD_INR": 83.25,
    "EUR_INR": 90.50,
    "GBP_INR": 105.30,
    "AED_INR": 22.67,
    "SGD_INR": 61.80,
    "JPY_INR": 0.56,
    "USD_EUR": 0.92,
    "EUR_USD": 1.09,
    "USD_GBP": 0.79,
    "GBP_USD": 1.27,
    "GBP_EUR": 1.16,
    "EUR_GBP": 0.86,
    "USD_CHF": 0.88,
    "CHF_USD": 1.14,
}

# =============================================================================
# DATA CLASSES
# =============================================================================

@dataclass
class CorrespondentBank:
    """Correspondent bank details."""
    name: str
    swift_code: str
    city: str
    country: str
    risk_rating: str
    account_number: str  # Masked


@dataclass
class SettlementWindow:
    """Settlement window timing."""
    start_time: str  # HH:MM UTC
    end_time: str
    cutoff_time: str
    timezone: str = "UTC"


@dataclass
class DailyDemand:
    """Single day demand record."""
    date: str
    amount: float
    settled_amount: float
    pending_amount: float
    num_transactions: int
    peak_hour_volume: float
    is_month_end: bool
    is_spike: bool


@dataclass
class Corridor:
    """Complete corridor data."""
    id: str
    code: str
    name: str
    source_currency: str
    destination_currency: str
    correspondent: Dict[str, Any]
    settlement_window: Dict[str, str]
    current_balance: float
    current_balance_local: float
    minimum_required: float
    recommended_balance: float
    statistics: Dict[str, float]
    config: Dict[str, Any]
    demand_history: List[Dict[str, Any]]
    created_at: str
    synthetic: bool = True


# =============================================================================
# GENERATOR FUNCTIONS
# =============================================================================

def generate_account_number() -> str:
    """Generate a masked account number."""
    last_four = random.randint(1000, 9999)
    return f"****{last_four}"


def generate_daily_demand(
    avg_volume: float,
    volatility: float,
    peak_multiplier: float,
    days: int = 90
) -> List[DailyDemand]:
    """
    Generate realistic daily demand patterns.
    
    Includes:
    - Weekly seasonality (higher Mon-Wed)
    - Monthly seasonality (higher end of month)
    - Random noise
    - Occasional spikes
    - Weekend reduction
    """
    demands = []
    base_date = datetime.now() - timedelta(days=days)
    
    for i in range(days):
        date = base_date + timedelta(days=i)
        day_of_week = date.weekday()
        day_of_month = date.day
        
        # Weekly seasonality
        if day_of_week < 3:  # Mon-Wed
            weekly_factor = 1.15
        elif day_of_week < 5:  # Thu-Fri
            weekly_factor = 0.95
        else:  # Weekend
            weekly_factor = 0.25  # Much lower on weekends
        
        # Monthly seasonality (higher end of month - salary payments, etc.)
        is_month_end = day_of_month > 25 or day_of_month < 5
        if is_month_end:
            monthly_factor = 1.25
        elif 10 <= day_of_month <= 15:  # Mid-month bump
            monthly_factor = 1.1
        else:
            monthly_factor = 1.0
        
        # Random noise
        if NUMPY_AVAILABLE:
            noise = np.random.normal(1.0, volatility)
        else:
            noise = 1.0 + random.gauss(0, volatility)
        noise = max(0.3, min(2.0, noise))  # Clamp
        
        # Occasional spikes (5% chance)
        is_spike = random.random() < 0.05
        spike_factor = random.uniform(peak_multiplier * 0.8, peak_multiplier) if is_spike else 1.0
        
        # Calculate demand
        demand = avg_volume * weekly_factor * monthly_factor * noise * spike_factor
        demand = max(0, demand)
        
        # Settlement split (90-95% settled same day)
        settlement_rate = random.uniform(0.90, 0.98)
        settled = demand * settlement_rate
        pending = demand - settled
        
        # Number of transactions (rough estimate)
        avg_transaction = random.uniform(50000, 200000)
        num_transactions = max(1, int(demand / avg_transaction))
        
        # Peak hour volume (typically 30-50% of daily in peak 2 hours)
        peak_hour_volume = demand * random.uniform(0.30, 0.50)
        
        demands.append(DailyDemand(
            date=date.strftime("%Y-%m-%d"),
            amount=round(demand, 2),
            settled_amount=round(settled, 2),
            pending_amount=round(pending, 2),
            num_transactions=num_transactions,
            peak_hour_volume=round(peak_hour_volume, 2),
            is_month_end=is_month_end,
            is_spike=is_spike
        ))
    
    return demands


def calculate_statistics(demands: List[DailyDemand]) -> Dict[str, float]:
    """Calculate statistical measures from demand history."""
    amounts = [d.amount for d in demands]
    
    if NUMPY_AVAILABLE:
        return {
            "avg_daily_volume": float(np.mean(amounts)),
            "median_daily_volume": float(np.median(amounts)),
            "std_daily_volume": float(np.std(amounts)),
            "min_daily_volume": float(np.min(amounts)),
            "max_daily_volume": float(np.max(amounts)),
            "p90_demand": float(np.percentile(amounts, 90)),
            "p95_demand": float(np.percentile(amounts, 95)),
            "p99_demand": float(np.percentile(amounts, 99)),
            "volatility": float(np.std(amounts) / np.mean(amounts)) if np.mean(amounts) > 0 else 0,
            "total_volume_90d": float(np.sum(amounts)),
            "spike_count": sum(1 for d in demands if d.is_spike),
            "weekend_avg": float(np.mean([d.amount for d in demands if datetime.strptime(d.date, "%Y-%m-%d").weekday() >= 5])) if any(datetime.strptime(d.date, "%Y-%m-%d").weekday() >= 5 for d in demands) else 0
        }
    else:
        sorted_amounts = sorted(amounts)
        n = len(amounts)
        mean_val = sum(amounts) / n
        variance = sum((x - mean_val) ** 2 for x in amounts) / n
        std_val = math.sqrt(variance)
        
        return {
            "avg_daily_volume": mean_val,
            "median_daily_volume": sorted_amounts[n // 2],
            "std_daily_volume": std_val,
            "min_daily_volume": min(amounts),
            "max_daily_volume": max(amounts),
            "p90_demand": sorted_amounts[int(n * 0.90)],
            "p95_demand": sorted_amounts[int(n * 0.95)],
            "p99_demand": sorted_amounts[int(n * 0.99)],
            "volatility": std_val / mean_val if mean_val > 0 else 0,
            "total_volume_90d": sum(amounts),
            "spike_count": sum(1 for d in demands if d.is_spike),
            "weekend_avg": 0
        }


def calculate_minimum_required(
    statistics: Dict[str, float],
    confidence_level: float = 0.95,
    safety_buffer: float = 0.05,
    fx_volatility: float = 0.02,
    correspondent_risk: float = 0.02
) -> Tuple[float, Dict[str, float]]:
    """
    Calculate minimum required balance with breakdown.
    
    Components:
    1. Base demand coverage (percentile-based)
    2. Safety buffer
    3. FX volatility reserve
    4. Correspondent risk margin
    """
    # Select percentile based on confidence level
    if confidence_level >= 0.99:
        base_demand = statistics["p99_demand"]
    elif confidence_level >= 0.95:
        base_demand = statistics["p95_demand"]
    else:
        base_demand = statistics["p90_demand"]
    
    # Calculate components
    safety_amount = base_demand * safety_buffer
    fx_reserve = base_demand * fx_volatility
    correspondent_margin = base_demand * correspondent_risk
    
    total = base_demand + safety_amount + fx_reserve + correspondent_margin
    
    breakdown = {
        "base_demand_coverage": round(base_demand, 2),
        "safety_buffer": round(safety_amount, 2),
        "fx_volatility_reserve": round(fx_reserve, 2),
        "correspondent_risk_margin": round(correspondent_margin, 2),
        "total_minimum_required": round(total, 2)
    }
    
    return total, breakdown


def generate_corridor(config: Dict[str, Any], corridor_id: int) -> Corridor:
    """Generate complete corridor data."""
    source = config["source"]
    dest = config["dest"]
    code = f"{source}_{dest}"
    
    # Select correspondent bank
    correspondents = CORRESPONDENT_BANKS.get(dest, CORRESPONDENT_BANKS["USD"])
    correspondent_data = random.choice(correspondents)
    
    correspondent = {
        "name": correspondent_data["name"],
        "swift_code": correspondent_data["swift"],
        "city": correspondent_data["city"],
        "country": get_country_for_currency(dest),
        "risk_rating": correspondent_data["rating"],
        "account_number": generate_account_number()
    }
    
    # Settlement window
    start_hour, end_hour = config["settlement_hours"]
    settlement_window = {
        "start_time": f"{start_hour:02d}:00",
        "end_time": f"{end_hour:02d}:00",
        "cutoff_time": f"{config['cutoff_hour']:02d}:00",
        "timezone": "UTC"
    }
    
    # Generate demand history
    demands = generate_daily_demand(
        avg_volume=config["avg_daily_volume"],
        volatility=config["volatility"],
        peak_multiplier=config["peak_multiplier"],
        days=90
    )
    
    # Calculate statistics
    statistics = calculate_statistics(demands)
    
    # Determine correspondent risk based on rating
    rating_risk_map = {"A+": 0.01, "A": 0.02, "A-": 0.03, "B+": 0.04, "B": 0.05}
    correspondent_risk = rating_risk_map.get(correspondent_data["rating"], 0.03)
    
    # Calculate minimum required
    minimum_required, breakdown = calculate_minimum_required(
        statistics=statistics,
        confidence_level=0.95,
        safety_buffer=0.05,
        fx_volatility=config["volatility"] * 0.5,  # Half of price volatility
        correspondent_risk=correspondent_risk
    )
    
    # Current balance (over-provisioned by 15-40%)
    over_provision = random.uniform(1.15, 1.40)
    current_balance = minimum_required * over_provision
    
    # Recommended balance (5% above minimum)
    recommended_balance = minimum_required * 1.05
    
    # Local currency balance
    fx_rate = BASE_FX_RATES.get(code, 1.0)
    current_balance_local = current_balance * fx_rate
    
    # Configuration
    corridor_config = {
        "confidence_level": 0.95,
        "safety_buffer_percent": 0.05,
        "fx_volatility_window_days": 30,
        "correspondent_risk_margin": correspondent_risk,
        "manual_floor": None,
        "is_locked": False,
        "auto_optimize": True,
        "alert_threshold_percent": 0.10
    }
    
    # Add breakdown to statistics
    statistics.update({
        "minimum_breakdown": breakdown,
        "over_provision_ratio": round(current_balance / minimum_required, 2),
        "excess_capital": round(current_balance - minimum_required, 2),
        "annual_opportunity_cost": round((current_balance - recommended_balance) * 0.05, 2)
    })
    
    return Corridor(
        id=f"corridor_{corridor_id}",
        code=code,
        name=f"{source} → {dest}",
        source_currency=source,
        destination_currency=dest,
        correspondent=correspondent,
        settlement_window=settlement_window,
        current_balance=round(current_balance, 2),
        current_balance_local=round(current_balance_local, 2),
        minimum_required=round(minimum_required, 2),
        recommended_balance=round(recommended_balance, 2),
        statistics=statistics,
        config=corridor_config,
        demand_history=[asdict(d) for d in demands],
        created_at=datetime.utcnow().isoformat(),
        synthetic=True
    )


def get_country_for_currency(currency: str) -> str:
    """Get country name for currency code."""
    mapping = {
        "USD": "United States",
        "EUR": "European Union",
        "GBP": "United Kingdom",
        "INR": "India",
        "AED": "United Arab Emirates",
        "SGD": "Singapore",
        "JPY": "Japan",
        "CHF": "Switzerland"
    }
    return mapping.get(currency, "Unknown")


def generate_fx_rates() -> Dict[str, Dict[str, Any]]:
    """Generate synthetic FX rates with realistic variation."""
    rates = {}
    timestamp = datetime.utcnow()
    
    for pair, base_rate in BASE_FX_RATES.items():
        # Add small random variation (±0.5%)
        variation = random.uniform(-0.005, 0.005)
        rate = base_rate * (1 + variation)
        
        # Calculate bid/ask spread
        spread = random.uniform(0.0005, 0.002)  # 5-20 bps
        bid = rate * (1 - spread / 2)
        ask = rate * (1 + spread / 2)
        
        rates[pair] = {
            "pair": pair,
            "mid_rate": round(rate, 6),
            "bid": round(bid, 6),
            "ask": round(ask, 6),
            "spread_bps": round(spread * 10000, 2),
            "timestamp": timestamp.isoformat(),
            "source": "synthetic"
        }
    
    return rates


def generate_bank_config() -> Dict[str, Any]:
    """Generate synthetic bank configuration."""
    return {
        "bank_name": "Demo Global Bank",
        "bank_code": "DEMOGB",
        "lei": "DEMO00000000000000XX",
        "headquarters": "Mumbai, India",
        "operating_mode": "shadow",
        
        "treasury_settings": {
            "opportunity_cost_rate": 0.05,
            "default_confidence_level": 0.95,
            "default_safety_buffer": 0.05,
            "optimization_frequency": "weekly",
            "approval_required": True,
            "min_approval_level": "treasury_manager"
        },
        
        "risk_settings": {
            "max_single_corridor_exposure": 0.25,
            "min_liquidity_ratio": 1.05,
            "stress_test_frequency": "monthly",
            "var_confidence": 0.99
        },
        
        "users": [
            {
                "id": "user_001",
                "name": "Demo User",
                "email": "treasury@demo-bank.com",
                "role": "treasury_analyst",
                "permissions": ["view", "run_optimization", "submit_approval"]
            },
            {
                "id": "user_002",
                "name": "J. Smith",
                "email": "j.smith@demo-bank.com",
                "role": "treasury_manager",
                "permissions": ["view", "run_optimization", "approve", "configure"]
            },
            {
                "id": "user_003",
                "name": "R. Sharma",
                "email": "r.sharma@demo-bank.com",
                "role": "risk_officer",
                "permissions": ["view", "approve", "stress_test", "audit"]
            }
        ],
        
        "integrations": {
            "core_banking": {"status": "mock", "last_sync": None},
            "swift": {"status": "mock", "last_sync": None},
            "market_data": {"status": "mock", "provider": "synthetic"}
        },
        
        "created_at": datetime.utcnow().isoformat(),
        "synthetic": True,
        "generation_seed": RANDOM_SEED
    }


def generate_transactions(
    corridors: List[Corridor],
    days: int = 7,
    transactions_per_day: int = 50
) -> List[Dict[str, Any]]:
    """Generate synthetic transaction records."""
    transactions = []
    base_date = datetime.now() - timedelta(days=days)
    
    transaction_types = ["PAYMENT", "RECEIPT", "TRANSFER", "SETTLEMENT"]
    statuses = ["COMPLETED", "PENDING", "PROCESSING"]
    
    for day in range(days):
        current_date = base_date + timedelta(days=day)
        
        # Skip weekends (fewer transactions)
        if current_date.weekday() >= 5:
            num_transactions = transactions_per_day // 5
        else:
            num_transactions = transactions_per_day
        
        for _ in range(num_transactions):
            corridor = random.choice(corridors)
            
            # Random time during business hours
            hour = random.randint(
                int(corridor.settlement_window["start_time"].split(":")[0]),
                int(corridor.settlement_window["end_time"].split(":")[0]) - 1
            )
            minute = random.randint(0, 59)
            second = random.randint(0, 59)
            
            timestamp = current_date.replace(hour=hour, minute=minute, second=second)
            
            # Transaction amount (log-normal distribution for realistic heavy tail)
            if NUMPY_AVAILABLE:
                amount = np.random.lognormal(mean=12, sigma=1.5)
            else:
                amount = random.lognormvariate(12, 1.5)
            amount = min(amount, 50_000_000)  # Cap at 50M
            
            # Generate transaction ID
            tx_id = f"TX{timestamp.strftime('%Y%m%d')}{random.randint(100000, 999999)}"
            
            # Reference
            if FAKER_AVAILABLE:
                reference = fake.bothify(text="REF-????-######")
                counterparty = fake.company()
            else:
                reference = f"REF-{random.randint(1000, 9999)}-{random.randint(100000, 999999)}"
                counterparty = f"Company {random.randint(1, 1000)}"
            
            transactions.append({
                "transaction_id": tx_id,
                "corridor_id": corridor.id,
                "corridor_code": corridor.code,
                "type": random.choice(transaction_types),
                "status": random.choices(statuses, weights=[0.85, 0.10, 0.05])[0],
                "amount": round(amount, 2),
                "currency": corridor.source_currency,
                "local_amount": round(amount * BASE_FX_RATES.get(corridor.code, 1.0), 2),
                "local_currency": corridor.destination_currency,
                "counterparty": counterparty,
                "reference": reference,
                "timestamp": timestamp.isoformat(),
                "settlement_date": (timestamp + timedelta(days=random.choice([0, 1]))).strftime("%Y-%m-%d"),
                "synthetic": True
            })
    
    # Sort by timestamp
    transactions.sort(key=lambda x: x["timestamp"])
    
    return transactions


def generate_audit_trail(num_records: int = 50) -> List[Dict[str, Any]]:
    """Generate synthetic audit trail records."""
    records = []
    base_date = datetime.now() - timedelta(days=30)
    
    event_types = [
        ("optimization_started", "System"),
        ("optimization_completed", "System"),
        ("approval_submitted", "A. Patel"),
        ("approval_decided", "J. Smith"),
        ("config_changed", "J. Smith"),
        ("data_refresh", "System"),
        ("user_login", "Various"),
        ("report_generated", "R. Sharma"),
    ]
    
    previous_hash = "0" * 64  # Genesis block
    
    for i in range(num_records):
        # Random timestamp
        days_ago = random.randint(0, 30)
        hours_ago = random.randint(0, 23)
        timestamp = base_date + timedelta(days=days_ago, hours=hours_ago)
        
        event_type, default_actor = random.choice(event_types)
        
        record = {
            "id": f"audit_{i:04d}",
            "timestamp": timestamp.isoformat(),
            "event_type": event_type,
            "actor": default_actor,
            "summary": generate_audit_summary(event_type),
            "details": {},
            "previous_hash": previous_hash
        }
        
        # Calculate hash
        record_data = json.dumps(record, sort_keys=True)
        record["hash"] = hashlib.sha256(record_data.encode()).hexdigest()
        previous_hash = record["hash"]
        
        records.append(record)
    
    # Sort by timestamp
    records.sort(key=lambda x: x["timestamp"])
    
    return records


def generate_audit_summary(event_type: str) -> str:
    """Generate human-readable audit summary."""
    summaries = {
        "optimization_started": "Optimization run initiated",
        "optimization_completed": f"Optimization completed successfully, {random.randint(5, 15)} corridors processed",
        "approval_submitted": "Optimization results submitted for approval",
        "approval_decided": random.choice(["Optimization approved", "Optimization rejected - market volatility"]),
        "config_changed": "Risk parameters updated",
        "data_refresh": "Daily corridor data refresh completed",
        "user_login": "User authenticated successfully",
        "report_generated": "Monthly treasury report generated",
    }
    return summaries.get(event_type, "Event recorded")


# =============================================================================
# MAIN GENERATOR
# =============================================================================

def generate_all_data(output_dir: Path, verbose: bool = True) -> Dict[str, Any]:
    """Generate all synthetic data files."""
    output_dir.mkdir(parents=True, exist_ok=True)
    
    summary = {
        "generated_at": datetime.utcnow().isoformat(),
        "seed": RANDOM_SEED,
        "files": []
    }
    
    if verbose:
        print("=" * 60)
        print("NOSTROQ SYNTHETIC DATA GENERATOR")
        print("=" * 60)
        print()
        print("⚠️  DISCLOSURE: All data generated is synthetic.")
        print("    No real banking data is used or sourced.")
        print()
    
    # 1. Generate corridors
    if verbose:
        print("📊 Generating corridors...")
    
    corridors = []
    for i, config in enumerate(CORRIDOR_CONFIGS):
        corridor = generate_corridor(config, corridor_id=34 + i)
        corridors.append(corridor)
    
    corridors_data = [asdict(c) for c in corridors]
    corridors_file = output_dir / "corridors.json"
    with open(corridors_file, "w") as f:
        json.dump(corridors_data, f, indent=2)
    
    summary["files"].append({"name": "corridors.json", "records": len(corridors)})
    
    if verbose:
        print(f"   ✓ Generated {len(corridors)} corridors")
    
    # 2. Generate FX rates
    if verbose:
        print("💱 Generating FX rates...")
    
    fx_rates = generate_fx_rates()
    fx_file = output_dir / "fx_rates.json"
    with open(fx_file, "w") as f:
        json.dump(fx_rates, f, indent=2)
    
    summary["files"].append({"name": "fx_rates.json", "records": len(fx_rates)})
    
    if verbose:
        print(f"   ✓ Generated {len(fx_rates)} FX rates")
    
    # 3. Generate bank config
    if verbose:
        print("🏦 Generating bank configuration...")
    
    bank_config = generate_bank_config()
    bank_file = output_dir / "bank_config.json"
    with open(bank_file, "w") as f:
        json.dump(bank_config, f, indent=2)
    
    summary["files"].append({"name": "bank_config.json", "records": 1})
    
    if verbose:
        print("   ✓ Generated bank configuration")
    
    # 4. Generate transactions
    if verbose:
        print("💸 Generating transactions...")
    
    transactions = generate_transactions(corridors, days=7, transactions_per_day=50)
    transactions_file = output_dir / "transactions.json"
    with open(transactions_file, "w") as f:
        json.dump(transactions, f, indent=2)
    
    summary["files"].append({"name": "transactions.json", "records": len(transactions)})
    
    if verbose:
        print(f"   ✓ Generated {len(transactions)} transactions")
    
    # 5. Generate audit trail
    if verbose:
        print("📝 Generating audit trail...")
    
    audit_records = generate_audit_trail(num_records=50)
    audit_file = output_dir / "audit_trail.json"
    with open(audit_file, "w") as f:
        json.dump(audit_records, f, indent=2)
    
    summary["files"].append({"name": "audit_trail.json", "records": len(audit_records)})
    
    if verbose:
        print(f"   ✓ Generated {len(audit_records)} audit records")
    
    # 6. Save summary
    summary_file = output_dir / "data_summary.json"
    with open(summary_file, "w") as f:
        json.dump(summary, f, indent=2)
    
    # Calculate totals
    total_liquidity = sum(c.current_balance for c in corridors)
    total_recommended = sum(c.recommended_balance for c in corridors)
    capital_release = total_liquidity - total_recommended
    
    if verbose:
        print()
        print("=" * 60)
        print("SUMMARY")
        print("=" * 60)
        print(f"Total Nostro Liquidity:  ${total_liquidity / 1_000_000:,.1f}M")
        print(f"Total Recommended:       ${total_recommended / 1_000_000:,.1f}M")
        print(f"Potential Release:       ${capital_release / 1_000_000:,.1f}M ({capital_release/total_liquidity*100:.1f}%)")
        print(f"Annual Savings (@ 5%):   ${capital_release * 0.05 / 1_000_000:,.1f}M")
        print()
        print(f"Output directory: {output_dir.absolute()}")
        print()
        print("✅ Synthetic data generation complete!")
    
    summary["totals"] = {
        "total_liquidity": total_liquidity,
        "total_recommended": total_recommended,
        "potential_release": capital_release,
        "release_percent": capital_release / total_liquidity * 100,
        "annual_savings_5pct": capital_release * 0.05
    }
    
    return summary


# =============================================================================
# CLI
# =============================================================================

def main():
    """Command-line interface."""
    parser = argparse.ArgumentParser(
        description="Generate synthetic data for NostroQ demonstration"
    )
    parser.add_argument(
        "--output", "-o",
        type=str,
        default="data",
        help="Output directory (default: data)"
    )
    parser.add_argument(
        "--seed", "-s",
        type=int,
        default=42,
        help="Random seed for reproducibility (default: 42)"
    )
    parser.add_argument(
        "--quiet", "-q",
        action="store_true",
        help="Suppress output"
    )
    
    args = parser.parse_args()
    
    # Update seed
    global RANDOM_SEED
    RANDOM_SEED = args.seed
    random.seed(RANDOM_SEED)
    if NUMPY_AVAILABLE:
        np.random.seed(RANDOM_SEED)
    if FAKER_AVAILABLE:
        Faker.seed(RANDOM_SEED)
    
    # Generate data
    output_dir = Path(args.output)
    generate_all_data(output_dir, verbose=not args.quiet)


if __name__ == "__main__":
    main()
